name: Build docker image

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build TLS
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false

      - name: Build non-TLS
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          build-args: |
            gitCommit: ${{ github.sha }}
            buildTag: conn_insecure

      - name: Update 'docker/README.md' and set the last tag version
        run: |
          sed "s/<TAG>/${{ github.ref_name }}/g" docker/README.template.md > docker/README.md

      - name: Commit updated README.md
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update README.md with latest tag ${{ github.ref_name }}"
          git push
